### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by dvaeversted** [aashley/nagios-livestatus-client#13]
In latest commit: 85f796313bb472d1268320c457f9dc626b7d244c

The library breaks compatibility with anything below PHP 7, by using a reserved keyword as method name.

> PHP Parse error:  syntax error, unexpected 'and' (T_LOGICAL_AND), expecting identifier (T_STRING) in Client.php on line 166

**Comment by tomsommer** [comment]
This is still not fixed, it is the function name that is the problem, not the variable...

**Comment by dvaeversted** [comment]
As @tomsommer says this is still not fixed. Since i can't re-open issue, i have filed a new one: #15
